
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.tema15.convertidor;

/**
 *
 * @author Usuario
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_titulo = new javax.swing.JLabel();
        l_introducirValor = new javax.swing.JLabel();
        tf_valorinicial = new javax.swing.JTextField();
        cb_cambioGrados = new javax.swing.JComboBox<>();
        l_introducirValor1 = new javax.swing.JLabel();
        l_resultado = new javax.swing.JLabel();
        tf_resultado = new javax.swing.JTextField();
        b_convertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l_titulo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        l_titulo.setForeground(new java.awt.Color(255, 0, 0));
        l_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_titulo.setText("CONVERTIDOR");

        l_introducirValor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_introducirValor.setText("Seleccione una opción:");

        tf_valorinicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_valorinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_valorinicialActionPerformed(evt);
            }
        });

        cb_cambioGrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ºC -----> ºF", "ºF -----> ºC" }));
        cb_cambioGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cambioGradosActionPerformed(evt);
            }
        });

        l_introducirValor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_introducirValor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_introducirValor1.setText("Introduce el valor a convertir:");

        l_resultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_resultado.setText("Resultado:");

        tf_resultado.setEditable(false);
        tf_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        b_convertir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        b_convertir.setForeground(new java.awt.Color(0, 0, 255));
        b_convertir.setText("Convertir");
        b_convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_convertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_resultado)
                            .addComponent(b_convertir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_introducirValor1)
                            .addComponent(l_introducirValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_valorinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_cambioGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_valorinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_introducirValor1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_introducirValor)
                    .addComponent(cb_cambioGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_convertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_resultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_valorinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_valorinicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_valorinicialActionPerformed

    private void cb_cambioGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cambioGradosActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_cb_cambioGradosActionPerformed

    private void b_convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_convertirActionPerformed
        // TODO add your handling code here:
        double numIngresado = Double.parseDouble(tf_valorinicial.getText());
        if(cb_cambioGrados.getSelectedItem().equals("ºC -----> ºF")){
            double cToF = 32+(9*numIngresado/5);
            tf_resultado.setText(cToF+" ºF");
        }else{
            double fToC = Math.round((numIngresado-32)*5/9);
            tf_resultado.setText(fToC+" ºC");
        }
    }//GEN-LAST:event_b_convertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_convertir;
    private javax.swing.JComboBox<String> cb_cambioGrados;
    private javax.swing.JLabel l_introducirValor;
    private javax.swing.JLabel l_introducirValor1;
    private javax.swing.JLabel l_resultado;
    private javax.swing.JLabel l_titulo;
    private javax.swing.JTextField tf_resultado;
    private javax.swing.JTextField tf_valorinicial;
    // End of variables declaration//GEN-END:variables
}
