/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        PanelFondoTitulo = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        cb_eleccion = new javax.swing.JComboBox<>();
        BotonAcceder = new javax.swing.JButton();
        LabelImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitulo.setFont(new java.awt.Font("Source Code Pro", 3, 30)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText("SISTEMA DE REPORTE DE EMPLEADOS");
        PanelPrincipal.add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 820, 50));

        PanelFondoTitulo.setBackground(new java.awt.Color(51, 204, 255));
        PanelFondoTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 6));

        javax.swing.GroupLayout PanelFondoTituloLayout = new javax.swing.GroupLayout(PanelFondoTitulo);
        PanelFondoTitulo.setLayout(PanelFondoTituloLayout);
        PanelFondoTituloLayout.setHorizontalGroup(
            PanelFondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        PanelFondoTituloLayout.setVerticalGroup(
            PanelFondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        PanelPrincipal.add(PanelFondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 600, 70));

        BotonSalir.setBackground(new java.awt.Color(0, 0, 0));
        BotonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 100, 50));

        cb_eleccion.setBackground(new java.awt.Color(51, 255, 255));
        cb_eleccion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cb_eleccion.setForeground(new java.awt.Color(0, 51, 153));
        cb_eleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informe Formulario", "Recibo Formulario", "Mostrar Fichero" }));
        cb_eleccion.setToolTipText("");
        cb_eleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_eleccionActionPerformed(evt);
            }
        });
        PanelPrincipal.add(cb_eleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 280, 60));

        BotonAcceder.setBackground(new java.awt.Color(90, 90, 90));
        BotonAcceder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonAcceder.setForeground(new java.awt.Color(255, 255, 153));
        BotonAcceder.setText("Acceder");
        BotonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccederActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, 50));

        LabelImagenFondo.setBackground(new java.awt.Color(255, 255, 255));
        LabelImagenFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoInterfaces\\src\\main\\java\\es\\medac\\Imagenes\\fondomenu.jpg")); // NOI18N
        LabelImagenFondo.setBorder(new javax.swing.border.MatteBorder(null));
        LabelImagenFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelPrincipal.add(LabelImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(MenuPrincipal.this, "¿Estas seguro que quieres cerrar la aplicación?",
                "Ventana salida.", JOptionPane.YES_NO_OPTION);
        if(opcion==JOptionPane.YES_OPTION){
            dispose();
        }
        
        
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccederActionPerformed
        // TODO add your handling code here:
       if(cb_eleccion.getSelectedItem().equals("Informe Formulario")){
            this.setVisible(false);
            InformeEmpleado p = new InformeEmpleado();
            p.setVisible(true);
        }else if(cb_eleccion.getSelectedItem().equals("Recibo Formulario")){
            this.setVisible(false);
            ReciboEmpleado r = new ReciboEmpleado();
            r.setVisible(true);
        }else if(cb_eleccion.getSelectedItem().equals("Mostrar Fichero")){
            this.setVisible(false);
            MostrarFichero m = new MostrarFichero();
            m.setVisible(true);
        }
    }//GEN-LAST:event_BotonAccederActionPerformed

    private void cb_eleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_eleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_eleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAcceder;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel LabelImagenFondo;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelFondoTitulo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JComboBox<String> cb_eleccion;
    // End of variables declaration//GEN-END:variables
}
